language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - wget http://getcomposer.org/composer.phar

install: php -d memory_limit=-1 composer.phar install --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text

notifications:
  email: wojciech.ciolko@aboutcoders.com
  hipchat:
    rooms:
      secure: uypSLOcHE2VlVWRlZFR0lwlj+1+I/oG10qAa3QA9LnJT6bIDGO9FBrKDvyhOhd/HmufQD35ytvrn2O3JUh9S25arjqoFEg4Or1MDymeUuSH6X1gV+pftDj/EEPTBZVNzpWOw+fCqASCmUsSFt6B9jd0QfnFMDbYKVaCS3Il+53+rRljvlCP55biFXOkHc4lsQ5FDJlal+5nmm8/SxGAN/IVnIfkHdHB+ljVKeU62F4OBLe0IiYvhmrgWt81D64zp96I5XvltvXT960QndIzVdp4rhB0L7GYxFiamiS9AhMcUVS4avlUwLbDtKQDe8VeKPxx2wsGwHD/zwjcs6QLxoyZfyofSRylhZYpuYLy938Wgl95euoA6gqfV4EtaTOkaVB/s1z6NuoAGPUEfFm8OvKJBxEX0/3hOsMdEsk5272WlTNyNRwNf0g2R2wS1y24OUZjSjroxKMZ3D77vX0xnmjzPecLkxpp5vGmNtBtP/eQ6PKwRPMPLBTUPsAlQzgU/BMQ/1WQKG9lBFHP62DXUlORxyZ6FuLat6gDTLayuPXNHoNFgTgnuCCx34n36MBSja1tQxY5ERglmzlk4tRARCCdww2TF0lFmgB00qesIzF0v3pXw/v84lj2r2XJ/cQFYDhZi3YF4VPLVVqxylOeREClWZ/xjYnDK/fm3JJpAf9M=
